################################################################################
[resync]

type = "register_array"
array_length = 30


# ------------------------------------------------------------------------------
[resync.data]

mode = "r_wpulse"
