################################################################################
[status]

idle.type = "bit"
idle.description = """
'1' when the module is inactive and a new run can be launched.

'0' when the module is working."""

counter.type = "integer"
counter.description = "Number of AXI bursts that have finished."
counter.max_value = 255


################################################################################
[command]

start.type = "bit"
start.description = "Start a read and write cycle."


################################################################################
[version]

mode = "r"
description = "Version number for this module"

version.type = "integer"
version.description = "Version field."
version.max_value = 255


################################################################################
[base_addresses]

type = "register_array"
array_length = 2


# ------------------------------------------------------------------------------
[base_addresses.read]

mode = "r_w"
description = "Where to read data from."

value.type = "bit_vector"
value.width = 28
value.description = "Address for a 256 MiB memory space."


# ------------------------------------------------------------------------------
[base_addresses.write]

mode = "r_w"
description = "Where to write data."


# ------------------------------------------------------------------------------
value.type = "bit_vector"
value.width = 28
value.description = "Address for a 256 MiB memory space."


################################################################################
[axi_data_width]

type = "constant"
value = 64
description = "Data width of the AXI port used by this module."


################################################################################
[burst_length_beats]

type = "constant"
value = 16
description = """
The burst length, in number of beats, that will be used by this module.
This value, in conjunction with **axi_data_width** gives the size of the memory buffer that will
be used.
"""
